version: '3.8'

services:
  # --- BASE DE DONNÉES POSTGRESQL ---
  db:
    image: postgres:15-alpine
    container_name: formation-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - formation-network

  # --- SERVEUR DE CAPTURE D'EMAILS (MAILHOG) ---
  mailhog:
    image: mailhog/mailhog:latest
    container_name: formation-mailhog
    ports:
      - "1025:1025" # Port SMTP pour que Spring Boot envoie les mails
      - "8025:8025" # Interface Web pour voir les mails reçus
    networks:
      - formation-network

  # --- BACKEND SPRING BOOT ---
  backend:
    build:
      context: ./backend
    container_name: formation-backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH_REQUIRED: ${SMTP_AUTH_REQUIRED}
      SMTP_STARTTLS_ENABLE: ${SMTP_STARTTLS_ENABLE}
      SPRING_PORT: ${SPRING_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      INVITATION_BASE_URL: ${INVITATION_BASE_URL:-http://localhost:4200/register}
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    depends_on:
      - db
      - mailhog
    networks:
      - formation-network

  # --- FRONTEND ANGULAR (servi par nginx) ---
  frontend:
    build:
      context: ./frontend
    container_name: formation-frontend
    ports:
      - "${ANGULAR_PORT}:80"
    depends_on:
      - backend
    networks:
      - formation-network

networks:
  formation-network:
    driver: bridge

volumes:
  postgres_data: