spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_formation
spring.datasource.username=postgres
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=I#ZogKha0BVQRK@U^D3ILH$c2iV3J0HKm80@5muD#YDCajYoOpXvFFGzUg*27gRIVESfT3TT3wP@dnmji#00y%GQjkxpzFG!ThNzt7@z9LTj89L&kB*75@GPgqhcaIbx
jwt.expiration=86400000

# Mail (désactivé en local)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
