spring.profiles.active=local
spring.application.name=backend
server.port=${SPRING_PORT:8080}

# --- CONFIGURATION DE LA BDD ---
spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURATION DU SERVEUR SMTP (EMAIL) ---
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH_REQUIRED}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE}
