# --- CONFIGURATION BDD LOCALE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_formation
spring.datasource.username=postgres
spring.datasource.password=password123

# --- CONFIGURATION SMTP LOCALE (valeurs fictives pour le dev) ---
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
